### ISSUE TITLE
[3.0.4] Published npm package missing files

### ISSUE THREAD

**Issue by shehi** [teodosii/react-notifications-component#100]
Hey there,

Published npm package is missing `src` folder, especially `.ts` files that are necessary for Typescript. Package even has `./dist/js/components/Notification.d.ts` file in it which imports non-existent `iNotification` from `src/types/Notification` which is missing.

**Comment by teodosii** [comment]
Turned out TS is stupid and it doesn't export interfaces from all files despite being imported from there. Moved interfaces to Notification.ts

You should now see all definitions in `Notification.d.ts`

![image](https://user-images.githubusercontent.com/40542072/112465599-94109b00-8d6d-11eb-99e6-5ba34aa3bfc2.png)

Fixed in `3.0.5`

Thanks for reporting the issue! Please try this on 3.0.5 and feel free to reopen it if you still have a problem.
Tested with CRA and the build is working.
