### ISSUE TITLE
Incompatibility with bulma css framework

### ISSUE THREAD

**Issue by Loque18** [teodosii/react-notifications-component#123]
First of all I want to thank for this wonderfull library. and now going straight to the issue there is a div with a class named "notification" which is a component in bulma css framework https://bulma.io/documentation/elements/notification/  

```
    return (
      <div
        ref={this.rootElementRef}
        onClick={click ? this.onClick : null}
        className="notification"
        style={parentStyle}
        onAnimationEnd={onAnimationEnd}
        onTransitionEnd={onTransitionEnd}
        onTouchStart={touchEnabled ? this.onTouchStart : null}
        onTouchMove={touchEnabled ? this.onTouchMove : null}
        onTouchEnd={touchEnabled ? this.onTouchEnd : null}
      >
        {content ? this.renderCustomContent() : this.renderNotification()}
      </div>
    );
```

please consider changing the name of that class

**Comment by teodosii** [comment]
Hey, thanks for reporting it. I'm not sure when but I'll put this with next release

**Comment by Loque18** [comment]
> Hey, thanks for reporting it. I'm not sure when but I'll put this with next release

Thank you so much for answering! Meanwhile for anyone else facing this problem, I suggest changing the class name for notification component in Bulma library, is located in /master/sass/elements/notification.sass

https://github.com/jgthms/bulma/blob/master/sass/elements/notification.sass

**Comment by teodosii** [comment]
I believe the containers will not be conflicting with other CSS classes (or at least I hope), therefore I've changed only the notification base class to be configurable by setting the `notificationBaseClass` prop. Unfortunately this means the CSS needs to be copied and changed accordingly as I don't know any way to have those classes changed based on the supplied prop. Not much of a big deal since I don't expect the CSS on this library to change anymore.

Watch for next release, it has this included
@Loque18
