### ISSUE TITLE
Events when notifications are clicked

### ISSUE THREAD

**Issue by HongSungMoon** [teodosii/react-notifications-component#14]
First, thanks for the cool module.

I want to generate an event when I click on the notification.
What can I do to trigger an event?

**Comment by teodosii** [comment]
Hey,
Unfortunately I'm afraid you can't do that easily. Only event currently supported is when the notification gets dismissed, event being called when the removal animation finishes.

You could use custom content, although I am not sure you'll be able to use the notification id. I think the way custom content is rendered should be modified, so that it it supplied the notification id.

May I ask you why you need to listen to the click event on the notification? Is it for removal or you need something else? If you don't need the notification id, you can easily use custom content to allow listening for click.

**Comment by HongSungMoon** [comment]
Thank you for your reply.

I am developing a web messenger. Notify when message is received. I want to give an event about when the notification is pressed. How can I get an event about when the animation ends?

**Comment by teodosii** [comment]
There's a prop named `onNotificationRemoval` on the component for that. It is documented in the readme file.

**Comment by guidogast** [comment]
It would seem to be a logical feature, though; Allow certain actions to be performed when the notification has been clicked. It would be a great addition without having to create custom components.
