### ISSUE TITLE
Project breaking due to "Removed default export"

### ISSUE THREAD

**Issue by koushikSen** [teodosii/react-notifications-component#142]
As per version 3.3.0, the default export was removed. We started a project development with version 3.0.4 and deployed the same version for a client.

2 days ago we had to do another deployment for a new client, as we were using  "react-notifications-component": "^3.0.4", it automatically installed the latest one. it caused an error in production due to the change in import syntax of React Notification component. 

My questions are 
 1. should it not be done as a major release as changing default export to named export will break applications that were using import syntax before 3.3.0?
 2. What could've been done to avoid the error in production?

**Comment by teodosii** [comment]
The problem was that I updated the package to use the `ts-loader` in order to export all types & interfaces. Due to an ordering issue on the loaders it never passed through the babel-loader, and one of the issues I did notice was about the default export. Since I had already released and the release was in an error state, had to come up with a solution and the solution was to remove the default export.

I can add it back now since the loaders are set in the correct order now but I don't see the point in it.

So to answer your questions
1. Maybe. Or maybe not. The release was in an an error state so it had to been fixed on that `3.X.Y`
2. Unfortunately if the release is in an error state, pretty much nothing except to downgrade or wait for library maintainer to publish a new fix.
