### ISSUE TITLE
Add several notification in one time

### ISSUE THREAD

**Issue by rumsterrt** [teodosii/react-notifications-component#16]
I am try to invoke addNotification in forEach when I get notifies from server, but on the screen i saw only one notify. I think problem in setState method (https://github.com/teodosii/react-notifications-component/blob/master/src/react-notification-component.js#L113) that used in addNotification method. May be you need to pass function as argument in setState and use prevState.notifications.data?

**Comment by teodosii** [comment]
Hmm, will investigate to see exactly what's the problem and provide a fix for that. I'm not sure if that is exactly the problem, `prevState.notifications` or `this.state.notifications` should point to the same data in this case, because `this.state` does not get mutated and there isn't any other call to setState in that method.

In the meanwhile, could you tell me which notification was displayed? The first, the last or randomly?

**Comment by rumsterrt** [comment]
@teodosii Last one notification displayed.

**Comment by teodosii** [comment]
Issue has been fixed. Could you please check on version `1.1.0` to see if build has been done correctly? Thanks
