### ISSUE TITLE
Width option no longer respected

### ISSUE THREAD

**Issue by zarsky-broad** [teodosii/react-notifications-component#26]
As of version 2.0.6, providing a `width` prop has no effect.

**Comment by teodosii** [comment]
Issue has been fixed in `2.0.7`

@wle8300 Thanks! `breakpoint` defines where should app change containers, it acts like a media query. Say, for example, 768px. If you resize and the window gets smaller than 768 then the component will switch to displaying the mobile containers - top and bottom only.  But it is only doing that if you set `isMobile` as well. Now that I'm thinking it might be confusing, these options may get merged into an object.

**Comment by wle8300** [comment]
Would it work if your removed isMobile and only kept breakpoint?

**Comment by teodosii** [comment]
It would work, I might do that for `2.0.8`. I doubt that people using it have set both `isMobile` to `false` and `breakpoint` as well. This is the only case that might get broken

**Comment by wle8300** [comment]
@teodosii Thanks for the new update! Really diggin this lib man! You have a unique talent for design + software! :smiley:
