### ISSUE TITLE
Notif width: is it a bug ?

### ISSUE THREAD

**Issue by theocerutti** [teodosii/react-notifications-component#32]
Hello,

I don't know why but the width of my notifications is weird.
Look: https://prnt.sc/pbuaob

Thanks !

**Comment by teodosii** [comment]
Need more details on this, otherwise I cannot help you.
In the inspector, what's the width being displayed for the notification?
Have you altered stylesheets in a way or another?
I can't figure out from the image how wide the notification is, but you have `width` option on notification to make it wider. I think the default width is set to `275px`, that might be too narrow for your content.
