### ISSUE TITLE
[Feature Request]: Allow showing buttons in notifications

### ISSUE THREAD

**Issue by varungupta85** [teodosii/react-notifications-component#95]
Allow providing an array of buttons such that user can also take some actions based on the alert. Since functions can't be serialized, the button handling can be done via events. A button could specify a `requestCode` when it is set up, and when the button is clicked, event `alertButtonClicked` could be emitted with request code as the data. A component that shows an alert can start listening on the event and handle based on the request code. The component can stop listening on the event when it is unmounted.

**Comment by teodosii** [comment]
Since this can be accomplished by using custom content notifications, I don't see the point in implementing it. The out of the box notifications need to be simple and match most of the use cases, which I think they do, while custom content on the other hand gives unlimited options.

Have you tried custom content notifications so far?
